name: Deploy to GitHub Pages

on:
  push:
    branches: "main" # Change to "master" if your primary branch uses that terminology

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Project Dependencies
        run: npm ci

      - name: Compile and Build Build Targets
        run: npm run build

      - name: Setup Pages Infrastructure Config
        uses: actions/configure-pages@v4

      - name: Upload Compiled Static Assets Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy Compiled Bundle Build to Live Environment
        id: deployment
        uses: actions/deploy-pages@v4